# Generated by Django 4.2.2 on 2023-06-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zipepreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='media/zipfile')),
                ('hours', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zipepreuve',
                'verbose_name_plural': 'Zipepreuves',
            },
        ),
    ]
