# Generated by Django 4.2.2 on 2023-06-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipepreuve',
            name='filename',
            field=models.FileField(upload_to='zipfile'),
        ),
    ]
