# Generated by Django 4.2.2 on 2023-06-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0002_alter_zipepreuve_filename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='images')),
            ],
        ),
    ]
