# Generated by Django 4.2.2 on 2023-06-12 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0004_attachment_date_ajout'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
