# Generated by Django 4.2.2 on 2023-06-14 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0006_fichierzip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fichierzip',
        ),
    ]
