# Generated by Django 4.2.2 on 2023-06-14 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0008_remove_image_image_image_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='Fichierzip',
        ),
    ]
