# Generated by Django 4.2.2 on 2023-07-02 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0010_fichierpdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FichierPDF',
            new_name='zipFile',
        ),
        migrations.DeleteModel(
            name='Fichierzip',
        ),
        migrations.DeleteModel(
            name='Zipepreuve',
        ),
    ]
