# Generated by Django 4.2.2 on 2023-07-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0011_rename_fichierpdf_zipfile_delete_fichierzip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='file',
            field=models.FileField(upload_to='zip_files'),
        ),
    ]
