# Generated by Django 4.2.2 on 2023-07-02 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0012_alter_zipfile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zipfile',
            old_name='file',
            new_name='filename',
        ),
    ]
