# Generated by Django 4.2.2 on 2023-07-02 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0013_rename_file_zipfile_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zipfile',
            name='filename',
            field=models.FileField(unique=True, upload_to='zip_files'),
        ),
    ]
