# Generated by Django 4.2.2 on 2023-07-02 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epreuveapk', '0014_alter_zipfile_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipfile',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
